version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tasks-api-app
    container_name: tasks-api-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - tasks-api

  web:
    image: nginx:alpine
    container_name: tasks-api-web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - tasks-api
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: tasks-api-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: tasks
      MYSQL_USER: tasks
      MYSQL_PASSWORD: tasks
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - tasks-api

networks:
  tasks-api:
    driver: bridge